### ISSUE TITLE
Scope Cosmos Explorer Support 

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-explorer#165]
Now that Trevor's research on scoping Cosmos scraper support in https://github.com/hyperlane-xyz/issues/issues/903 is completed, and implementation issues are in https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3329/, we should figure out what this will take on the Explorer side.

```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/61
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/80
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/81
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/82
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/88
```
