### ISSUE TITLE
Epic: Improve Explorer

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/hyperlane-explorer#166]
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/issues/issues/735
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3787
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/74
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/160
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/159
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/161
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2237
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/163
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/65
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/78
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/79
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/162
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1639
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2122
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2199
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/64
- [ ] https://github.com/hyperlane-xyz/issues/issues/1203
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/158
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3448
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3641
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3837
- [ ] https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1578
- [ ] https://github.com/hyperlane-xyz/hyperlane-explorer/issues/86
```

```[tasklist]
### Performance
- [ ] https://github.com/hyperlane-xyz/issues/issues/1060
```
